package Interfaces;

import Codigo.Servidor;
import Codigo.ServidorImp;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.SwingUtilities;

public class PanelAerovias extends javax.swing.JPanel {
    private DefaultListModel<String> aeroviaMadridBarcelonaModel;
    private DefaultListModel<String> aeroviaBarcelonaMadridModel;
    /**
     * Creates new form PanelAerovias
     */
    public PanelAerovias() {
        initComponents();
        aeroviaMadridBarcelonaModel = new DefaultListModel<>();
        aeroviaBarcelonaMadridModel = new DefaultListModel<>();
        jListAeroviaMadridBarcelona.setModel(aeroviaMadridBarcelonaModel);
        jListAeroviaBarcelonaMadrid.setModel(aeroviaBarcelonaMadridModel);
    }
    public void annadirElemListaAeroviaMadridBarcelona(String text) {
        DefaultListModel model = (DefaultListModel) jListAeroviaMadridBarcelona.getModel();
        model.addElement(text);
        
    }
    public void eliminarElemListaAeroviaMadridBarcelona(String text){
        DefaultListModel model = (DefaultListModel) jListAeroviaMadridBarcelona.getModel();
        int index = -1;
        for(int i = 0; i < model.getSize(); i++){
            if(text.equals(model.get(i))){
                index = i;
                break;
            }
        }
        if(index != -1){
            model.remove(index);
        }
        
    }
    public void annadirElemListaAeroviaBarcelonaMadrid(String text) {
        DefaultListModel model = (DefaultListModel) jListAeroviaBarcelonaMadrid.getModel();
        model.addElement(text);
    }
    public void eliminarElemListaAeroviaBarcelonaMadrid(String text){
        DefaultListModel model = (DefaultListModel) jListAeroviaBarcelonaMadrid.getModel();
        int index = -1;
        for(int i = 0; i < model.getSize(); i++){
            if(text.equals(model.get(i))){
                index = i;
                break;
            }
        }
        if(index != -1){
            model.remove(index);
        }
        
    }
    public void actualizarAerovias(){
        try {
                // Conectar al registro RMI en el servidor
                Registry registry = LocateRegistry.getRegistry("localhost", 1099);

                // Obtener la referencia remota del objeto del servidor
                Servidor servidor = (Servidor) registry.lookup("Servidor");

                // Usar los métodos remotos
                SwingUtilities.invokeLater(() -> {
                    try {
                        jListAeroviaBarcelonaMadrid.setModel(servidor.avionesAerovia1());
                        jListAeroviaMadridBarcelona.setModel(servidor.avionesAerovia2());
                    } catch (RemoteException ex) {
                        Logger.getLogger(PanelAerovias.class.getName()).log(Level.SEVERE, null, ex);
                    }
                });
            } catch (Exception e) {
                System.err.println("Error en el cliente RMI al actualizar Aerovias: " + e.getMessage());
        }
        
    }
    public DefaultListModel<String> getModelAeroviaMadridBarcelona(){
        return aeroviaMadridBarcelonaModel;
    }
    public DefaultListModel<String> getModelAeroviaBarcelonaMadrid(){
        return aeroviaBarcelonaMadridModel;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelAeroviaMadridBarcelona = new javax.swing.JLabel();
        jLabelAeroviaBarcelonaMadrid = new javax.swing.JLabel();
        jScrollPaneProductos3 = new javax.swing.JScrollPane();
        jListAeroviaMadridBarcelona = new javax.swing.JList<>();
        jScrollPaneProductos4 = new javax.swing.JScrollPane();
        jListAeroviaBarcelonaMadrid = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelAeroviaBarcelonaMadrid1 = new javax.swing.JLabel();

        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(325, 640));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelAeroviaMadridBarcelona.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAeroviaMadridBarcelona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAeroviaMadridBarcelona.setText("Madrid-Barcelona");
        add(jLabelAeroviaMadridBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 25));

        jLabelAeroviaBarcelonaMadrid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelAeroviaBarcelonaMadrid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAeroviaBarcelonaMadrid.setText("Barcelona-madrid");
        add(jLabelAeroviaBarcelonaMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, -1, 25));

        jListAeroviaMadridBarcelona.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jListAeroviaMadridBarcelona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAeroviaMadridBarcelonaMouseClicked(evt);
            }
        });
        jScrollPaneProductos3.setViewportView(jListAeroviaMadridBarcelona);

        add(jScrollPaneProductos3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 121, 536));

        jListAeroviaBarcelonaMadrid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jListAeroviaBarcelonaMadrid.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListAeroviaBarcelonaMadridMouseClicked(evt);
            }
        });
        jScrollPaneProductos4.setViewportView(jListAeroviaBarcelonaMadrid);

        add(jScrollPaneProductos4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 125, 536));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, 536));

        jLabelAeroviaBarcelonaMadrid1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelAeroviaBarcelonaMadrid1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelAeroviaBarcelonaMadrid1.setText("Aerovías");
        add(jLabelAeroviaBarcelonaMadrid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 104, 25));
    }// </editor-fold>//GEN-END:initComponents

    private void jListAeroviaMadridBarcelonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAeroviaMadridBarcelonaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListAeroviaMadridBarcelonaMouseClicked

    private void jListAeroviaBarcelonaMadridMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListAeroviaBarcelonaMadridMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jListAeroviaBarcelonaMadridMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAeroviaBarcelonaMadrid;
    private javax.swing.JLabel jLabelAeroviaBarcelonaMadrid1;
    private javax.swing.JLabel jLabelAeroviaMadridBarcelona;
    private javax.swing.JList<String> jListAeroviaBarcelonaMadrid;
    private javax.swing.JList<String> jListAeroviaMadridBarcelona;
    private javax.swing.JScrollPane jScrollPaneProductos3;
    private javax.swing.JScrollPane jScrollPaneProductos4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
